/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPremiumRouteImport } from './routes/_app/premium'
import { Route as AppDeveloperPortalRouteImport } from './routes/_app/developer-portal'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomizationRouteImport } from './routes/_app/customization'
import { Route as AppGuildsGuildIdTicketsRouteImport } from './routes/_app/guilds/$guildId/tickets'
import { Route as AppGuildsGuildIdOverviewRouteImport } from './routes/_app/guilds/$guildId/overview'
import { Route as AppGuildsGuildIdCustomCommandsRouteImport } from './routes/_app/guilds/$guildId/custom-commands'
import { Route as AppGuildsGuildIdBotRouteImport } from './routes/_app/guilds/$guildId/bot'
import { Route as AppGuildsGuildIdApplicationsRouteImport } from './routes/_app/guilds/$guildId/applications'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiumRoute = AppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppRoute,
} as any)
const AppDeveloperPortalRoute = AppDeveloperPortalRouteImport.update({
  id: '/developer-portal',
  path: '/developer-portal',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomizationRoute = AppCustomizationRouteImport.update({
  id: '/customization',
  path: '/customization',
  getParentRoute: () => AppRoute,
} as any)
const AppGuildsGuildIdTicketsRoute = AppGuildsGuildIdTicketsRouteImport.update({
  id: '/guilds/$guildId/tickets',
  path: '/guilds/$guildId/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppGuildsGuildIdOverviewRoute =
  AppGuildsGuildIdOverviewRouteImport.update({
    id: '/guilds/$guildId/overview',
    path: '/guilds/$guildId/overview',
    getParentRoute: () => AppRoute,
  } as any)
const AppGuildsGuildIdCustomCommandsRoute =
  AppGuildsGuildIdCustomCommandsRouteImport.update({
    id: '/guilds/$guildId/custom-commands',
    path: '/guilds/$guildId/custom-commands',
    getParentRoute: () => AppRoute,
  } as any)
const AppGuildsGuildIdBotRoute = AppGuildsGuildIdBotRouteImport.update({
  id: '/guilds/$guildId/bot',
  path: '/guilds/$guildId/bot',
  getParentRoute: () => AppRoute,
} as any)
const AppGuildsGuildIdApplicationsRoute =
  AppGuildsGuildIdApplicationsRouteImport.update({
    id: '/guilds/$guildId/applications',
    path: '/guilds/$guildId/applications',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/customization': typeof AppCustomizationRoute
  '/dashboard': typeof AppDashboardRoute
  '/developer-portal': typeof AppDeveloperPortalRoute
  '/premium': typeof AppPremiumRoute
  '/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guilds/$guildId/applications': typeof AppGuildsGuildIdApplicationsRoute
  '/guilds/$guildId/bot': typeof AppGuildsGuildIdBotRoute
  '/guilds/$guildId/custom-commands': typeof AppGuildsGuildIdCustomCommandsRoute
  '/guilds/$guildId/overview': typeof AppGuildsGuildIdOverviewRoute
  '/guilds/$guildId/tickets': typeof AppGuildsGuildIdTicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/customization': typeof AppCustomizationRoute
  '/dashboard': typeof AppDashboardRoute
  '/developer-portal': typeof AppDeveloperPortalRoute
  '/premium': typeof AppPremiumRoute
  '/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guilds/$guildId/applications': typeof AppGuildsGuildIdApplicationsRoute
  '/guilds/$guildId/bot': typeof AppGuildsGuildIdBotRoute
  '/guilds/$guildId/custom-commands': typeof AppGuildsGuildIdCustomCommandsRoute
  '/guilds/$guildId/overview': typeof AppGuildsGuildIdOverviewRoute
  '/guilds/$guildId/tickets': typeof AppGuildsGuildIdTicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/customization': typeof AppCustomizationRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/developer-portal': typeof AppDeveloperPortalRoute
  '/_app/premium': typeof AppPremiumRoute
  '/_app/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_app/guilds/$guildId/applications': typeof AppGuildsGuildIdApplicationsRoute
  '/_app/guilds/$guildId/bot': typeof AppGuildsGuildIdBotRoute
  '/_app/guilds/$guildId/custom-commands': typeof AppGuildsGuildIdCustomCommandsRoute
  '/_app/guilds/$guildId/overview': typeof AppGuildsGuildIdOverviewRoute
  '/_app/guilds/$guildId/tickets': typeof AppGuildsGuildIdTicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/customization'
    | '/dashboard'
    | '/developer-portal'
    | '/premium'
    | '/settings'
    | '/auth/callback'
    | '/guilds/$guildId/applications'
    | '/guilds/$guildId/bot'
    | '/guilds/$guildId/custom-commands'
    | '/guilds/$guildId/overview'
    | '/guilds/$guildId/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/customization'
    | '/dashboard'
    | '/developer-portal'
    | '/premium'
    | '/settings'
    | '/auth/callback'
    | '/guilds/$guildId/applications'
    | '/guilds/$guildId/bot'
    | '/guilds/$guildId/custom-commands'
    | '/guilds/$guildId/overview'
    | '/guilds/$guildId/tickets'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/customization'
    | '/_app/dashboard'
    | '/_app/developer-portal'
    | '/_app/premium'
    | '/_app/settings'
    | '/auth/callback'
    | '/_app/guilds/$guildId/applications'
    | '/_app/guilds/$guildId/bot'
    | '/_app/guilds/$guildId/custom-commands'
    | '/_app/guilds/$guildId/overview'
    | '/_app/guilds/$guildId/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/premium': {
      id: '/_app/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AppPremiumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer-portal': {
      id: '/_app/developer-portal'
      path: '/developer-portal'
      fullPath: '/developer-portal'
      preLoaderRoute: typeof AppDeveloperPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customization': {
      id: '/_app/customization'
      path: '/customization'
      fullPath: '/customization'
      preLoaderRoute: typeof AppCustomizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guilds/$guildId/tickets': {
      id: '/_app/guilds/$guildId/tickets'
      path: '/guilds/$guildId/tickets'
      fullPath: '/guilds/$guildId/tickets'
      preLoaderRoute: typeof AppGuildsGuildIdTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guilds/$guildId/overview': {
      id: '/_app/guilds/$guildId/overview'
      path: '/guilds/$guildId/overview'
      fullPath: '/guilds/$guildId/overview'
      preLoaderRoute: typeof AppGuildsGuildIdOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guilds/$guildId/custom-commands': {
      id: '/_app/guilds/$guildId/custom-commands'
      path: '/guilds/$guildId/custom-commands'
      fullPath: '/guilds/$guildId/custom-commands'
      preLoaderRoute: typeof AppGuildsGuildIdCustomCommandsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guilds/$guildId/bot': {
      id: '/_app/guilds/$guildId/bot'
      path: '/guilds/$guildId/bot'
      fullPath: '/guilds/$guildId/bot'
      preLoaderRoute: typeof AppGuildsGuildIdBotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guilds/$guildId/applications': {
      id: '/_app/guilds/$guildId/applications'
      path: '/guilds/$guildId/applications'
      fullPath: '/guilds/$guildId/applications'
      preLoaderRoute: typeof AppGuildsGuildIdApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCustomizationRoute: typeof AppCustomizationRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDeveloperPortalRoute: typeof AppDeveloperPortalRoute
  AppPremiumRoute: typeof AppPremiumRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppGuildsGuildIdApplicationsRoute: typeof AppGuildsGuildIdApplicationsRoute
  AppGuildsGuildIdBotRoute: typeof AppGuildsGuildIdBotRoute
  AppGuildsGuildIdCustomCommandsRoute: typeof AppGuildsGuildIdCustomCommandsRoute
  AppGuildsGuildIdOverviewRoute: typeof AppGuildsGuildIdOverviewRoute
  AppGuildsGuildIdTicketsRoute: typeof AppGuildsGuildIdTicketsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCustomizationRoute: AppCustomizationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDeveloperPortalRoute: AppDeveloperPortalRoute,
  AppPremiumRoute: AppPremiumRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppGuildsGuildIdApplicationsRoute: AppGuildsGuildIdApplicationsRoute,
  AppGuildsGuildIdBotRoute: AppGuildsGuildIdBotRoute,
  AppGuildsGuildIdCustomCommandsRoute: AppGuildsGuildIdCustomCommandsRoute,
  AppGuildsGuildIdOverviewRoute: AppGuildsGuildIdOverviewRoute,
  AppGuildsGuildIdTicketsRoute: AppGuildsGuildIdTicketsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
